language: C

perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:

before_script:
  - sudo ./setup/build-thirdparty.sh /opt/znapzend/thirdparty
  - sudo ./setup/build-devel.sh /opt/znapzend/thirdparty

script:
  - ./configure --prefix=/opt/znapzend
  - sudo make install
  - perl -I/opt/znapzend/thirdparty/lib/perl5 -MDevel::Cover /opt/znapzend/bin/znapzend --help || test $? == 1 
  - perl -I/opt/znapzend/thirdparty/lib/perl5 -MDevel::Cover /opt/znapzend/bin/znapzendzetup --help || test $? == 1 
  - perl -I/opt/znapzend/thirdparty/lib/perl5 -MDevel::Cover /opt/znapzend/bin/znapzendztats --help || test $? == 1 
  - env PERL5LIB=/opt/znapzend/thirdparty/lib/perl5  /opt/znapzend/thirdparty/bin/cover -report coveralls

