language: perl

perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

# disable dependency install
install:
  - true

before_script:
  - ./setup/build-thirdparty.sh $HOME/znapzend/thirdparty
  - ./setup/build-devel.sh $HOME/znapzend/thirdparty

script:
  - ./configure --prefix=$HOME/znapzend
  - make install
  - perl -I$HOME/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/znapzend.t $HOME/znapzend || test $? == 1 
  - perl -I$HOME/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/znapzendzetup.t $HOME/znapzend || test $? == 1 
  - perl -I$HOME/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/znapzendztatz.t $HOME/znapzend || test $? == 1 
  - perl -I$HOME/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/autoscrub.t $HOME/znapzend || test $? == 1 
  - env PERL5LIB=$HOME/znapzend/thirdparty/lib/perl5  $HOME/znapzend/thirdparty/bin/cover -report coveralls

