language: C

perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  cpanm -n Devel::Cover::Report::Coveralls

before_script:
  - sudo ./setup/build-thirdparty.sh /opt/znapzend/thirdparty

script:
  - ./configure --prefix=/opt/znapzend
  - sudo make install
  - perl -MDevel::Cover /opt/znapzend/bin/znapzend --help || test $? == 1 
  - perl -MDevel::Cover /opt/znapzend/bin/znapzendzetup --help || test $? == 1 
  - cover -test -report coveralls

